// <auto-generated />
using System;
using CapstoneApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CapstoneApi.Migrations
{
    [DbContext(typeof(CapstoneContext))]
    [Migration("20181126230913_RegistrationEntities")]
    partial class RegistrationEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CapstoneApi.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("End");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CapstoneApi.Models.Registrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhotoRelease");

                    b.HasKey("Id");

                    b.ToTable("Registrants");
                });

            modelBuilder.Entity("CapstoneApi.Models.RegistrantRegistration", b =>
                {
                    b.Property<Guid>("RegistrationId");

                    b.Property<Guid>("RegistrantId");

                    b.HasKey("RegistrationId", "RegistrantId");

                    b.HasIndex("RegistrantId");

                    b.ToTable("RegistrantRegistration");
                });

            modelBuilder.Entity("CapstoneApi.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EventId");

                    b.Property<Guid?>("PrimaryContactId");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PrimaryContactId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("CapstoneApi.Models.RegistrantRegistration", b =>
                {
                    b.HasOne("CapstoneApi.Models.Registrant", "Registrant")
                        .WithMany("RegistrantRegistrations")
                        .HasForeignKey("RegistrantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CapstoneApi.Models.Registration", "Registration")
                        .WithMany("RegistrantRegistrations")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CapstoneApi.Models.Registration", b =>
                {
                    b.HasOne("CapstoneApi.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId");

                    b.HasOne("CapstoneApi.Models.Registrant", "PrimaryContact")
                        .WithMany("PrimaryRegistrations")
                        .HasForeignKey("PrimaryContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
